const federativeUnits = [
  { name: "Acre", federativeUnit: "AC" },
  { name: "Alagoas", federativeUnit: "AL" },
  { name: "Amapá", federativeUnit: "AP" },
  { name: "Amazonas", federativeUnit: "AM" },
  { name: "Bahia", federativeUnit: "BA" },
  { name: "Ceará", federativeUnit: "CE" },
  { name: "Distrito Federal", federativeUnit: "DF" },
  { name: "Espírito Santo", federativeUnit: "ES" },
  { name: "Goiás", federativeUnit: "GO" },
  { name: "Maranhão", federativeUnit: "MA" },
  { name: "Mato Grosso", federativeUnit: "MT" },
  { name: "Mato Grosso do Sul", federativeUnit: "MS" },
  { name: "Minas Gerais", federativeUnit: "MG" },
  { name: "Pará", federativeUnit: "PA" },
  { name: "Paraíba", federativeUnit: "PB" },
  { name: "Paraná", federativeUnit: "PR" },
  { name: "Pernambuco", federativeUnit: "PE" },
  { name: "Piauí", federativeUnit: "PI" },
  { name: "Rio de Janeiro", federativeUnit: "RJ" },
  { name: "Rio Grande do Norte", federativeUnit: "RN" },
  { name: "Rio Grande do Sul", federativeUnit: "RS" },
  { name: "Rondônia", federativeUnit: "RO" },
  { name: "Roraima", federativeUnit: "RR" },
  { name: "Santa Catarina", federativeUnit: "SC" },
  { name: "São Paulo", federativeUnit: "SP" },
  { name: "Sergipe", federativeUnit: "SE" },
  { name: "Tocantins", federativeUnit: "TO" },
];

export default federativeUnits;
